### PR TITLE
Fixes for EdgeTX, no need for specific OTX and ETX versions, other tweaks

### PR DESCRIPTION
**Pull request by pfeerick**
Firstly, thanks for making this script... I had been thinking for a while that I needed a 'simple' reference for the stick commands, and nearly went the way of a couple of images stored on the transmitter, but this is much nicer :)

With EdgeTX 2.5 introducing colour themes, `TEXT_COLOR` should no longer be manipulated as it will effect system colours as well as the colours within the script. Hence the use of `CUSTOM_COLOR` instead. 

The EdgeTX version of the script also works on OpenTX - the compatibility issue is more one of black and white display vs colorlcd. Also, the install location and method of access is much simpler via the tools menu. And it's possible to set the display name of the script. So I've done this as a couple of commits to help break down the changes, and also some screenshots of the send result on both EdgeTX and OpenTX. Please let me know if you want any changes made and do with as you see fit!

Happy Easter! :) 

EdgeTX:
image

OpenTX:
image

### CODE REVIEW

**Comment by DHaacke** [comment]
Peter:

What wonderful enhancements! Your help is much appreciated!  I’ll get your code right now.

I’ve pretty much done away with all my radios and migrated to the Mambo, so I don’t have EdgeTx, but of course, even if I did it would still be 128 x 64 and B&W. So your updates really make this sweet!  

Do happen to have a Mambo or radio with a 128x64 screen. I’d like to get your thoughts on another script I’ve been tinkering with (if you're at all interested) that will show switch, pot and button settings in screen, which would be helpful when switching between model and aircraft types and have poor short term memory like me.

Again, thanks for you input and expertise!

-Doug

**Comment by pfeerick** [comment]
Mambo, no, but I do have both 128x64 (Radiomaster TX12, Jumper TLite, etc) and 212x64 (Frsky X9D+2019) B&W screen radios running EdgeTX also. 

And yes, that does sound useful... it's what I like about [Switch2](https://www.rcgroups.com/forums/showpost.php?p=47009445&postcount=3793) and also having model notes to remind WTH I set the switches to for different models. :) My Lua knowledge is limited (I'm more into the C++ coding of the actual EdgeTX firmware) but I'm more than happy to help out where I can, or pester some of the other Lua gurus ;)

**Comment by DHaacke** [comment]
Yeah, I’m a developer by trade, and Lua takes some getting used to…. 

I’ll send some code for you to review when I have something presentable.. probably in the next few days..

Thanks!

Doug

**Comment by DHaacke** [comment]
Peter:

> Message ID: ***@***.***>
>
> Here’s the new script (sorry for the wait)…  Again, this is a utility to
help a pilot remember what stick, button or pot does what depending in the
model.  Since it uses pages, it’ll need to go in the Tools folder.  I’ve
temporary called it Switch Viewer. When you run it, it’ll have three
models, and use the Page button to page through each model. When you toggle
a switch or button, it will show a short message on what that switch will
do depending on position.

Take a look, tell me what you like and don’t like, or any other comments.

The pots don’t show any text, and I’m trying to think of the best way to
handle that, as I do use them for Volume and Beeper on some models, but
also Volume and VTX power on others. Still working on that, but space for
more text is at a premium.

Anyway, thanks for having a look when you have time, and I look forward to
your suggestion or ways to improve the code.

Cheers, and happy flying!

-Doug

**Comment by pfeerick** [comment]
Hey Doug... emails through github don't keep attachments, etc... 

You can send me an email via pfeerick@trashmail.fr and I'll reply back from my normal account... that is a disposable email redirect.

**Comment by DHaacke** [comment]
Sorry, forgot about that….

Here you go…

-Doug

**Comment by DHaacke** [comment]
Dammit… I’ll get it this time...

**Pull request merged**
